spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
token:
  expiration_time: 86400000
  secret: my-token-dev
gateway:
  ip: 172.30.1.34
order_service:
  url: http://localhost:8000/order-service/%s/orders
